### PR TITLE
added services section in navbar

### PR DESCRIPTION
**Pull request by devrudra9**
Previously services section was not in the navbar 
Screenshot 2023-10-23 034501

Added the services section to every other page(sections) of the navbar which takes user to that page on clicking.
Screenshot 2023-10-23 034636

### CODE REVIEW

**Comment by devrudra9** [comment]
Hi Divya, Please merge my PR #50

**Comment by Iamdivyak** [comment]
this is not planned. But ideally, you should raise an issue, get assigned then start coding, and if you are happy with the code, make a pull request

**Comment by devrudra9** [comment]
Hi Divya, I haven't made any changes that would affect the ui of the website, I just added the pre-built services page in the navbar section. 
I don't see any issues here.
Overall its completely your wish whether you want to merge it or not.

**Comment by Iamdivyak** [comment]
I am sorry that your efforts were not accepted. but that's the reason issues are made for. I didn't want this change in the website if you raised an issue I would have told you that it was not the plan. your time wasn't wasted. we would like to see you contribute to this project. thankyou @devrudra9

**Pull request closed without merging**
