### PR TITLE
feature: formvaildation and form setup

### PR DESCRIPTION
**Pull request by weberankit**
#38 added form validation and form setup
image

### CODE REVIEW

**Comment by weberankit** [comment]
plz activate the link so that the form can start working

**Comment by Iamdivyak** [comment]
image
 
you have deleted an impotent line of code. something like
<main-footer></main-footer>

**Comment by weberankit** [comment]
@Iamdivyak What I have deleted could you please explain more

**Comment by weberankit** [comment]
image
here only this part is edited as to submit form I have added the method and link to action but have not deleted anything important

**Comment by weberankit** [comment]
image
nothing changed

**Comment by weberankit** [comment]
I have added 35 new lines and changed 4 lines (in which one line is completely  changed )

**Comment by Iamdivyak** [comment]
yes, my bad. someone else deleted the footer. you have done great work I'm merging your code. thanks for contributing:)

**Pull request merged**
