### PR TITLE
"Design Updates: 'Area of Expertise' Section 

### PR DESCRIPTION
**Pull request by Akshit203**
Hi @Iamdivyak 

I've made some design changes in Area of Expertise section

Screenshot 2023-10-29 001832

could you please consider merging this pull request ?

Thank you !

### CODE REVIEW

**Comment by Iamdivyak** [comment]
Remove pricing section code. That wasn't assigned to you. Someone else is working on it

**Comment by Akshit203** [comment]
I've removed the pricing section code.
Please review the updated pull request and consider merging it.

**Comment by Iamdivyak** [comment]
you have deleted my PDF CV file and some photos too.

**Comment by Iamdivyak** [comment]
Please clone the repo again and make changes only for the area of expertise section. and make a pull request. keep in mind do not delete any file, photo, or pdf

**Comment by Akshit203** [comment]
Ok

**Comment by Iamdivyak** [comment]
feel free to add photos but don't delete anything.

**Pull request closed without merging**
