### PR TITLE
fix issue #63

### PR DESCRIPTION
**Pull request by Honeshwar**
**Take a look**

### CODE REVIEW

**Comment by Iamdivyak** [comment]
no. something like this [button prototype](https://www.figma.com/proto/wKcuUSuG9uEbaXL4TytRzG/my-profile%2Fportfolio-design?page-id=0%3A1&type=design&node-id=1434-8&viewport=1304%2C-2226%2C0.3&t=99u4WloS2JhWIF4h-1&scaling=scale-down&starting-point-node-id=1434%3A8&show-proto-sidebar=1&mode=design)

**Comment by Honeshwar** [comment]
Okay, got it.

**Comment by Honeshwar** [comment]
Check this one.

**Comment by Iamdivyak** [comment]
add some delay to change the background wheel hovering

**Pull request merged**
