### PR TITLE
added shadow and green gradient to all buttons on hover and wrote new headlines 

### LINKED ISSUE #25: Grammatical Errors
I saw some grammatical errors in the website which might leave bad impression on potential client or employer, i wish to work on that and improvise it with more effective tag lines, Assign this to me under hacktoberfest

### PR DESCRIPTION
**Pull request by bilaljaved01**
I have tried to make the simple tacky home button into a pleasing button which turns gradient green and has shadow , 
if you liked this, accept this hacktoberfest-accepted label
fixes #25 too

### CODE REVIEW

**Comment by Iamdivyak** [comment]
could you please add the same effect to the rest of the buttons?
so that it could match the theme!!

**Comment by bilaljaved01** [comment]
I can do that, just don't forget to label it under hacktoberfest

**Comment by bilaljaved01** [comment]
all buttons changed, kindly check

**Comment by Iamdivyak** [comment]
resolve conflicts

**Comment by bilaljaved01** [comment]
kindly review

**Comment by Iamdivyak** [comment]
image

ideally submit button shouldn't look like this👆🏻

**Comment by bilaljaved01** [comment]
Sure, let me take a look

**Comment by bilaljaved01** [comment]
all is done, you can review it finally

**Comment by Iamdivyak** [comment]
kindly make another pull request for issue no:  #25

**Comment by Iamdivyak** [comment]
by doing this you can get 2 pull request acceptance in hacktoberfest

**Comment by Iamdivyak** [comment]
also, it will be easy for me to review.

**Comment by bilaljaved01** [comment]
Okay sure

**Pull request closed without merging**
